apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scrapetester
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bjossi86/scrapetester.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: scrapetester-namespace
  syncPolicy:
    automated:
      prune: true
